[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true